# Generated by Django 3.2.13 on 2022-06-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_contact_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Imageurl', models.CharField(default='False', max_length=200)),
                ('About', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=10)),
                ('Facebook_url', models.TextField(max_length=50)),
                ('Instagram_url', models.TextField(max_length=50)),
                ('Mail_url', models.TextField(max_length=50)),
                ('Twitter_url', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=20)),
                ('Imageurl', models.CharField(default='False', max_length=200)),
                ('About', models.TextField(max_length=200)),
                ('status', models.TextField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=10)),
                ('Facebook_url', models.TextField(max_length=50)),
                ('Instagram_url', models.TextField(max_length=50)),
                ('Mail_url', models.TextField(max_length=50)),
                ('Twitter_url', models.TextField(max_length=50)),
            ],
        ),
    ]
