# Generated by Django 4.0.5 on 2022-07-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_contributor_donator'),
        ('authentication', '0003_querymodel'),
    ]

    operations = [
    ]
