# Generated by Django 3.2.13 on 2022-07-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_contributor_donator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_Pic', models.CharField(default='False', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('LastLogin', models.DateTimeField(auto_now=True)),
                ('DateJoined', models.DateTimeField(auto_now_add=True)),
                ('usertype', models.CharField(choices=[('A', 'Admin'), ('U', 'User')], default='U', max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], max_length=5)),
                ('Age', models.IntegerField()),
                ('Mobile_Number', models.IntegerField()),
            ],
        ),
    ]
