# Generated by Django 4.0.5 on 2022-07-02 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_merge_0003_contributor_donator_0003_querymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('patient_no', models.IntegerField(max_length=6)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('age', models.IntegerField(max_length=3)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('disease_name', models.CharField(max_length=50)),
                ('treatment_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('additional_file_url', models.CharField(max_length=50)),
                ('verification', models.TextField(choices=[('V', 'Verified'), ('U', 'Unverified')], max_length=10)),
                ('status', models.TextField(choices=[('E', 'Enabled'), ('D', 'Disabled')], max_length=10)),
                ('ratings', models.IntegerField(choices=[('1', 'VeryBad'), ('2', 'Bad'), ('3', 'Okay'), ('4', 'Good'), ('5', 'Excellent')], default=3)),
                ('case_no', models.IntegerField(max_length=5)),
                ('title', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AskSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('patient_no', models.IntegerField(max_length=6)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('age', models.IntegerField(max_length=3)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('disease_name', models.CharField(max_length=50)),
                ('symptoms', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('additional_file_url', models.CharField(max_length=50)),
                ('current_condition', models.CharField(max_length=255)),
                ('query', models.CharField(max_length=255)),
                ('case_no', models.IntegerField(max_length=5)),
                ('title', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
