# Generated by Django 4.0.6 on 2022-07-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_shareexp_asksuggestion'),
        ('authentication', '0006_profile_user'),
    ]

    operations = [
    ]
