# Generated by Django 4.0.6 on 2022-07-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_merge_0005_shareexp_asksuggestion_0006_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asksuggestion',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='shareexp',
            old_name='treatment_name',
            new_name='pathy_name',
        ),
        migrations.RenameField(
            model_name='shareexp',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='asksuggestion',
            name='patient_no',
        ),
        migrations.RemoveField(
            model_name='shareexp',
            name='patient_no',
        ),
        migrations.AlterField(
            model_name='shareexp',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10),
        ),
    ]
