# Generated by Django 4.0.6 on 2022-07-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_rename_user_asksuggestion_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='disease_names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('disease_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='pathy_names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pathy_code', models.CharField(max_length=10)),
            ],
        ),
    ]
