# Generated by Django 4.0.6 on 2022-07-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_disease_names_pathy_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease_names',
            name='disease_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pathy_names',
            name='pathy_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
